test:
  image: node:14
  services:
    - postgres:9.6.16
  variables:
    DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
  script:
    - npm install
    - npm test
